/**
 * EMV QR Code specification constants - Essential only
 */

/**
 * EMV Tag constants for KHQR
 */
export const EMV_TAGS = {
  // Standard EMV tags
  PAYLOAD_FORMAT_INDICATOR: '00',
  POINT_OF_INITIATION_METHOD: '01',
  MERCHANT_ACCOUNT_INFORMATION_INDIVIDUAL: '29',
  MERCHANT_ACCOUNT_INFORMATION_MERCHANT: '30',
  MERCHANT_CATEGORY_CODE: '52',
  TRANSACTION_CURRENCY: '53',
  TRANSACTION_AMOUNT: '54',
  COUNTRY_CODE: '58',
  MERCHANT_NAME: '59',
  MERCHANT_CITY: '60',
  ADDITIONAL_DATA_TAG: '62',
  CRC: '63',
  MERCHANT_INFORMATION_LANGUAGE_TEMPLATE: '64',
  TIMESTAMP_TAG: '99',

  // UnionPay specific
  UNIONPAY_MERCHANT_ACCOUNT: '15',

  // Sub-tags for merchant account information
  BAKONG_ACCOUNT_IDENTIFIER: '00',
  MERCHANT_ACCOUNT_INFORMATION_MERCHANT_ID: '01',
  INDIVIDUAL_ACCOUNT_INFORMATION: '01',
  MERCHANT_ACCOUNT_INFORMATION_ACQUIRING_BANK: '02',

  // Additional data sub-tags
  BILLNUMBER_TAG: '01',
  ADDITIONAL_DATA_FIELD_MOBILE_NUMBER: '02',
  STORELABEL_TAG: '03',
  TERMINAL_TAG: '07',
  PURPOSE_OF_TRANSACTION: '08',

  // Timestamp sub-tags
  CREATION_TIMESTAMP: '00',
  EXPIRATION_TIMESTAMP: '01',

  // Language template sub-tags
  LANGUAGE_PREFERENCE: '00',
  MERCHANT_NAME_ALTERNATE_LANGUAGE: '01',
  MERCHANT_CITY_ALTERNATE_LANGUAGE: '02',
} as const

/**
 * EMV default values
 */
export const EMV_DEFAULTS = {
  PAYLOAD_FORMAT_INDICATOR: '01',
  MERCHANT_CATEGORY_CODE: '5999',
  COUNTRY_CODE: 'KH',
  MERCHANT_CITY: 'Phnom Penh',
  CRC_LENGTH: '04',
} as const

/**
 * QR Type indicators
 */
export const QR_TYPE_INDICATORS = {
  STATIC_QR: '11',
  DYNAMIC_QR: '12',
} as const

/**
 * Maximum field lengths for validation
 */
export const MAX_LENGTHS = {
  KHQR: 12,
  MERCHANT_NAME: 25,
  BAKONG_ACCOUNT: 32,
  MERCHANT_CATEGORY_CODE: 4,
  MERCHANT_CITY: 15,
  TRANSACTION_AMOUNT: 14,
  TRANSACTION_CURRENCY: 3,
  COUNTRY_CODE: 2,
  BILL_NUMBER: 25,
  STORE_LABEL: 25,
  TERMINAL_LABEL: 25,
  PURPOSE_OF_TRANSACTION: 25,
  MERCHANT_ID: 32,
  ACQUIRING_BANK: 32,
  MOBILE_NUMBER: 25,
  ACCOUNT_INFORMATION: 32,
  UPI_MERCHANT: 99,
  LANGUAGE_PREFERENCE: 2,
  MERCHANT_NAME_ALTERNATE_LANGUAGE: 25,
  MERCHANT_CITY_ALTERNATE_LANGUAGE: 15,
} as const

/**
 * Currency codes for KHQR
 */
export const CURRENCY_CODES = {
  KHR: '116',
  USD: '840',
} as const
