import { createSchema } from '@better-fetch/fetch'
import { z } from 'zod'
import { baseResponse } from '../constant'

export const $schema = createSchema(
  {
    '/v1/renew_token': {
      method: 'post',
      input: z.object({
        /** Your registered email */
        email: z
          .email()
          .min(1, 'email is required')
          .max(30, 'email is too long'),
      }),
      output: baseResponse.extend({
        data: z.object({
          token: z.string().min(1, 'token is required'),
        }),
      }),
    },

    '/v1/generate_deeplink_by_qr': {
      method: 'post',
      input: z.object({
        /** QR code string generated by KHQR SDK */
        qr: z.string().min(1, 'qr is required'),
        sourceInfo: z.object({
          /** Your app icon public URL */
          appIconUrl: z.url().min(1, 'appIconUrl is required'),
          /** Your app name */
          appName: z.string().min(1, 'appName is required'),
          /** Deeplink URL for opening your app after payment is completed */
          appDeepLinkCallback: z
            .string()
            .url()
            .min(1, 'appDeepLinkCallback is required'),
        }),
      }),
      output: baseResponse.extend({
        data: z.object({
          /** Generated short links will be different every time api is called and also depend on which api url is being used */
          shortLink: z.string(),
        }),
      }),
    },

    '/v1/check_transaction_by_md5': {
      method: 'post',
      input: z.object({
        /** MD5 hash string generated by KHQR SDK */
        md5: z.string().min(1, 'md5 is required'),
      }),
      output: baseResponse.extend({
        data: z.object({
          hash: z.string(),
          fromAccountId: z.string(),
          toAccoundId: z.string(),
          currency: z.string(),
          amount: z.number(),
          description: z.string(),
          createdDateMs: z.string(),
          acknowledgedDateMs: z.enum(['PENDING', 'COMPLETED', 'FAILED']),
        }),
      }),
    },
    '/v1/check_transaction_by_hash': {},
    '/v1/check_transaction_by_short_hash': {},
  },
  {
    strict: true,
  }
)
